<?php

/**
* From https://drupal.stackexchange.com/a/253282
*
* Changes "Published" label to something more descriptive.
*
* Implements hook_entity_bundle_field_info().
*
*/

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\Entity\BaseFieldOverride;

function scs_publish_ad_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions) {
  $fields = [];

  // Whether the hook implementation was called for our group type.
  if ($entity_type->id() == 'node' && in_array($bundle, ['job_advertisement']) && !empty($base_field_definitions['status-value']['label'])) {
    // Create a base field override with custom title.
    $field = BaseFieldOverride::createFromBaseFieldDefinition($base_field_definitions['status-value'], $bundle);
    $field->setLabel(t('Check this box when you are ready to submit this proposal, then click the Save button below.'));
    $field->setDefaultValue(false);
    $fields['status-value'] = $field;
  }

  return $fields;
}